# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('omniforms', '0004_omnislugfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='DummyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('agree', models.BooleanField()),
                ('some_date', models.DateField(blank=True, null=True)),
                ('some_date_1', models.DateField(auto_now=True)),
                ('some_date_2', models.DateField(auto_now_add=True)),
                ('some_datetime', models.DateTimeField()),
                ('some_datetime_1', models.DateTimeField(auto_now=True)),
                ('some_datetime_2', models.DateTimeField(auto_now_add=True)),
                ('some_decimal', models.DecimalField(decimal_places=10, max_digits=12)),
                ('some_email', models.EmailField(max_length=254)),
                ('some_float', models.FloatField()),
                ('some_integer', models.IntegerField()),
                ('some_time', models.TimeField()),
                ('some_time_1', models.TimeField(auto_now=True)),
                ('some_time_2', models.TimeField(auto_now_add=True)),
                ('some_url', models.URLField()),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='DummyModel2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TaggableManagerField',
            fields=[
                ('omnifield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='omniforms.OmniField')),
            ],
            bases=('omniforms.omnifield',),
        ),
        migrations.CreateModel(
            name='TaggableManagerInvalidField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='dummymodel',
            name='other_models',
            field=models.ManyToManyField(to='tests.DummyModel2'),
        ),
    ]
