# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DummyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('agree', models.BooleanField()),
                ('some_date', models.DateField(blank=True, null=True)),
                ('some_datetime', models.DateTimeField()),
                ('some_decimal', models.DecimalField(decimal_places=10, max_digits=12)),
                ('some_email', models.EmailField(max_length=254)),
                ('some_float', models.FloatField()),
                ('some_integer', models.IntegerField()),
                ('some_time', models.TimeField()),
                ('some_url', models.URLField()),
            ],
        ),
    ]
