# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('omniforms', '0003_auto_20160609_1336'),
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaggableManagerField',
            fields=[
                ('omnifield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='omniforms.OmniField')),
            ],
            bases=('omniforms.omnifield',),
        ),
    ]
