# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DummyModel2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='dummymodel',
            name='other_models',
            field=models.ManyToManyField(to='tests.DummyModel2'),
        ),
    ]
