# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_taggablemanagerfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaggableManagerInvalidField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
