# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('omniforms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OmniFormSaveInstanceHandler',
            fields=[
                ('omniformhandler_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='omniforms.OmniFormHandler')),
            ],
            bases=('omniforms.omniformhandler',),
        ),
    ]
