# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('omniforms', '0002_omniformsaveinstancehandler'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='omniformemailhandler',
            options={'verbose_name': 'Send Email'},
        ),
        migrations.AlterModelOptions(
            name='omniformsaveinstancehandler',
            options={'verbose_name': 'Save Data'},
        ),
        migrations.AlterField(
            model_name='omnimodelform',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.ContentType'),
        ),
    ]
