# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 08:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('omniforms', '0005_omnifilefield'),
    ]

    operations = [
        migrations.CreateModel(
            name='OmniImageField',
            fields=[
                ('omnifield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='omniforms.OmniField')),
            ],
            bases=('omniforms.omnifield',),
        ),
    ]
