# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 07:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omniforms', '0006_omniimagefield'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='omnifield',
            unique_together=set([('name', 'content_type', 'object_id')]),
        ),
    ]
