# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 07:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('omniforms', '0007_auto_20160613_0729'),
    ]

    operations = [
        migrations.CreateModel(
            name='OmniDurationField',
            fields=[
                ('omnifield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='omniforms.OmniField')),
                ('initial', models.DurationField(blank=True, null=True)),
            ],
            bases=('omniforms.omnifield',),
        ),
        migrations.CreateModel(
            name='OmniGenericIPAddressField',
            fields=[
                ('omnifield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='omniforms.OmniField')),
                ('initial', models.GenericIPAddressField(blank=True, null=True)),
            ],
            bases=('omniforms.omnifield',),
        ),
        migrations.CreateModel(
            name='OmniUUIDField',
            fields=[
                ('omnifield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='omniforms.OmniField')),
                ('initial', models.UUIDField(blank=True, null=True)),
            ],
            bases=('omniforms.omnifield',),
        ),
    ]
