# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omniforms', '0008_omnidurationfield_omnigenericipaddressfield_omniuuidfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='omnicharfield',
            name='max_length',
            field=models.PositiveIntegerField(blank=True, default=255),
        ),
        migrations.AddField(
            model_name='omnicharfield',
            name='min_length',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
