# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omniforms', '0009_auto_20160614_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='omnigenericipaddressfield',
            name='protocol',
            field=models.CharField(blank=True, choices=[('both', 'Both'), ('IPv4', 'IPv4'), ('IPv6', 'IPv6')], default='both', max_length=4),
        ),
        migrations.AddField(
            model_name='omnigenericipaddressfield',
            name='unpack_ipv4',
            field=models.BooleanField(default=False),
        ),
    ]
