# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omniforms', '0010_auto_20160614_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='omniurlfield',
            name='max_length',
            field=models.PositiveIntegerField(blank=True, default=255),
        ),
        migrations.AddField(
            model_name='omniurlfield',
            name='min_length',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
