# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omniforms', '0013_auto_20160614_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='omnifloatfield',
            name='max_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='omnifloatfield',
            name='min_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
