# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omniforms', '0014_auto_20160614_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='omniintegerfield',
            name='max_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='omniintegerfield',
            name='min_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
