# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omniforms', '0015_auto_20160614_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='omnifilefield',
            name='allow_empty_file',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='omnifilefield',
            name='max_length',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
