# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-12 08:53
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omniforms', '0017_auto_20160616_0440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='omnibooleanfield',
            options={'verbose_name': 'Boolean Field'},
        ),
        migrations.AlterModelOptions(
            name='omnicharfield',
            options={'verbose_name': 'Char Field'},
        ),
        migrations.AlterModelOptions(
            name='omnidatefield',
            options={'verbose_name': 'Date Field'},
        ),
        migrations.AlterModelOptions(
            name='omnidatetimefield',
            options={'verbose_name': 'DateTime Field'},
        ),
        migrations.AlterModelOptions(
            name='omnidecimalfield',
            options={'verbose_name': 'Decimal Field'},
        ),
        migrations.AlterModelOptions(
            name='omnidurationfield',
            options={'verbose_name': 'Duration Field'},
        ),
        migrations.AlterModelOptions(
            name='omniemailfield',
            options={'verbose_name': 'Email Field'},
        ),
        migrations.AlterModelOptions(
            name='omnifield',
            options={'ordering': ('order',), 'verbose_name': 'Field'},
        ),
        migrations.AlterModelOptions(
            name='omnifilefield',
            options={'verbose_name': 'File Field'},
        ),
        migrations.AlterModelOptions(
            name='omnifloatfield',
            options={'verbose_name': 'Float Field'},
        ),
        migrations.AlterModelOptions(
            name='omniforeignkeyfield',
            options={'verbose_name': 'Foreign Key Field'},
        ),
        migrations.AlterModelOptions(
            name='omnigenericipaddressfield',
            options={'verbose_name': 'IP Address Field'},
        ),
        migrations.AlterModelOptions(
            name='omniimagefield',
            options={'verbose_name': 'Image Field'},
        ),
        migrations.AlterModelOptions(
            name='omniintegerfield',
            options={'verbose_name': 'Integer Field'},
        ),
        migrations.AlterModelOptions(
            name='omnimanytomanyfield',
            options={'verbose_name': 'Many To Many Field'},
        ),
        migrations.AlterModelOptions(
            name='omnislugfield',
            options={'verbose_name': 'Slug Field'},
        ),
        migrations.AlterModelOptions(
            name='omnitimefield',
            options={'verbose_name': 'Time Field'},
        ),
        migrations.AlterModelOptions(
            name='omniurlfield',
            options={'verbose_name': 'URL Field'},
        ),
        migrations.AlterModelOptions(
            name='omniuuidfield',
            options={'verbose_name': 'UUID Field'},
        ),
        migrations.AlterField(
            model_name='omnibooleanfield',
            name='initial',
            field=models.NullBooleanField(help_text='If provided, initial data will appear in this field by default.'),
        ),
        migrations.AlterField(
            model_name='omnicharfield',
            name='initial',
            field=models.TextField(blank=True, help_text='If provided, initial data will appear in this field by default.', null=True),
        ),
        migrations.AlterField(
            model_name='omnicharfield',
            name='max_length',
            field=models.PositiveIntegerField(blank=True, default=255, help_text='The maximum amount of data that can be entered into this field'),
        ),
        migrations.AlterField(
            model_name='omnicharfield',
            name='min_length',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='The minimum amount of data that can be entered into this field'),
        ),
        migrations.AlterField(
            model_name='omnidatefield',
            name='initial',
            field=models.DateField(blank=True, help_text='If provided, initial data will appear in this field by default.', null=True),
        ),
        migrations.AlterField(
            model_name='omnidatetimefield',
            name='initial',
            field=models.DateTimeField(blank=True, help_text='If provided, initial data will appear in this field by default.', null=True),
        ),
        migrations.AlterField(
            model_name='omnidecimalfield',
            name='decimal_places',
            field=models.PositiveIntegerField(help_text='The expected number of decimal places that must be entered into this field'),
        ),
        migrations.AlterField(
            model_name='omnidecimalfield',
            name='initial',
            field=models.DecimalField(blank=True, decimal_places=100, help_text='If provided, initial data will appear in this field by default.', max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='omnidecimalfield',
            name='max_digits',
            field=models.PositiveIntegerField(help_text='The maximum number of digits that may be entered into this field'),
        ),
        migrations.AlterField(
            model_name='omnidecimalfield',
            name='max_value',
            field=models.DecimalField(blank=True, decimal_places=100, help_text='The maximum value that may be entered into this field', max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='omnidecimalfield',
            name='min_value',
            field=models.DecimalField(blank=True, decimal_places=100, help_text='The minimum value that may be entered into this field', max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='omnidurationfield',
            name='initial',
            field=models.DurationField(blank=True, help_text='If provided, initial data will appear in this field by default.', null=True),
        ),
        migrations.AlterField(
            model_name='omniemailfield',
            name='initial',
            field=models.EmailField(blank=True, help_text='If provided, initial data will appear in this field by default.', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='omniemailfield',
            name='max_length',
            field=models.PositiveIntegerField(blank=True, default=255, help_text='The maximum amount of data that can be entered into this field'),
        ),
        migrations.AlterField(
            model_name='omniemailfield',
            name='min_length',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='The minimum amount of data that can be entered into this field'),
        ),
        migrations.AlterField(
            model_name='omnifield',
            name='help_text',
            field=models.TextField(blank=True, help_text='Provide any information that may assist users in filling out this form field here', null=True),
        ),
        migrations.AlterField(
            model_name='omnifield',
            name='label',
            field=models.CharField(help_text="Appears next to the form field and should identify it's purpose. Example, for an email field this could be 'Email address'", max_length=255),
        ),
        migrations.AlterField(
            model_name='omnifield',
            name='name',
            field=models.CharField(help_text='The name of this field. May only contain alphanumeric characters and underscores. Must start and end with an alphanumeric character.', max_length=255, validators=[django.core.validators.RegexValidator(code='invalid_field_name', message='The name may only contain alphanumeric characters and underscores.', regex='^[a-z0-9_]+$')]),
        ),
        migrations.AlterField(
            model_name='omnifield',
            name='order',
            field=models.IntegerField(default=0, help_text='Determines where this field appears relative to other fields in the form. Smaller values cause the field to float to the top of the form, larger numbers cause the field to sink to the bottom of the form'),
        ),
        migrations.AlterField(
            model_name='omnifield',
            name='required',
            field=models.BooleanField(default=False, help_text='If checked, users must provide data within this field. If not checked the field is optional'),
        ),
        migrations.AlterField(
            model_name='omnifield',
            name='widget_class',
            field=models.CharField(help_text='Determines how the field is displayed in the generated form', max_length=255),
        ),
        migrations.AlterField(
            model_name='omnifilefield',
            name='allow_empty_file',
            field=models.BooleanField(default=False, help_text='If checked empty files may be uploaded using this field. Otherwise uploaded files may not be empty'),
        ),
        migrations.AlterField(
            model_name='omnifilefield',
            name='max_length',
            field=models.PositiveIntegerField(blank=True, help_text='The maximum amount of data that can be entered into this field', null=True),
        ),
        migrations.AlterField(
            model_name='omnifloatfield',
            name='initial',
            field=models.FloatField(blank=True, help_text='If provided, initial data will appear in this field by default.', null=True),
        ),
        migrations.AlterField(
            model_name='omnifloatfield',
            name='max_value',
            field=models.FloatField(blank=True, help_text='The maximum value that may be entered into this field', null=True),
        ),
        migrations.AlterField(
            model_name='omnifloatfield',
            name='min_value',
            field=models.FloatField(blank=True, help_text='The minimum value that may be entered into this field', null=True),
        ),
        migrations.AlterField(
            model_name='omnigenericipaddressfield',
            name='initial',
            field=models.GenericIPAddressField(blank=True, help_text='If provided, initial data will appear in this field by default.', null=True),
        ),
        migrations.AlterField(
            model_name='omnigenericipaddressfield',
            name='protocol',
            field=models.CharField(blank=True, choices=[('both', 'Both'), ('IPv4', 'IPv4'), ('IPv6', 'IPv6')], default='both', help_text='Please select which protocol data entered into this field must adhere to', max_length=4),
        ),
        migrations.AlterField(
            model_name='omnigenericipaddressfield',
            name='unpack_ipv4',
            field=models.BooleanField(default=False, help_text='If checked IPV4 addresses will be unpacked'),
        ),
        migrations.AlterField(
            model_name='omniintegerfield',
            name='initial',
            field=models.IntegerField(blank=True, help_text='If provided, initial data will appear in this field by default.', null=True),
        ),
        migrations.AlterField(
            model_name='omniintegerfield',
            name='max_value',
            field=models.IntegerField(blank=True, help_text='The maximum value that may be entered into this field', null=True),
        ),
        migrations.AlterField(
            model_name='omniintegerfield',
            name='min_value',
            field=models.IntegerField(blank=True, help_text='The minimum value that may be entered into this field', null=True),
        ),
        migrations.AlterField(
            model_name='omnislugfield',
            name='initial',
            field=models.SlugField(blank=True, help_text='If provided, initial data will appear in this field by default.', null=True),
        ),
        migrations.AlterField(
            model_name='omnitimefield',
            name='initial',
            field=models.TimeField(blank=True, help_text='If provided, initial data will appear in this field by default.', null=True),
        ),
        migrations.AlterField(
            model_name='omniurlfield',
            name='initial',
            field=models.URLField(blank=True, help_text='If provided, initial data will appear in this field by default.', null=True),
        ),
        migrations.AlterField(
            model_name='omniurlfield',
            name='max_length',
            field=models.PositiveIntegerField(blank=True, default=255, help_text='The maximum amount of data that can be entered into this field'),
        ),
        migrations.AlterField(
            model_name='omniurlfield',
            name='min_length',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='The minimum amount of data that can be entered into this field'),
        ),
        migrations.AlterField(
            model_name='omniuuidfield',
            name='initial',
            field=models.UUIDField(blank=True, help_text='If provided, initial data will appear in this field by default.', null=True),
        ),
    ]
