# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-23 04:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('omniforms', '0020_omnichoicefield_omnimultiplechoicefield'),
    ]

    operations = [
        migrations.CreateModel(
            name='OmniFormEmailConfirmationHandler',
            fields=[
                ('omniformhandler_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='omniforms.OmniFormHandler')),
                ('subject', models.CharField(help_text='The subject of the email that will be sent', max_length=255)),
                ('template', models.TextField()),
                ('recipient_field', models.ForeignKey(help_text='The field on the associated form used for collecting the users email address. Note that if this field is optional and not filled in by the user the confirmation email will not be sent', on_delete=django.db.models.deletion.PROTECT, to='omniforms.OmniEmailField')),
            ],
            options={
                'verbose_name': 'Send Email Confirmation',
            },
            bases=('omniforms.omniformhandler',),
        ),
        migrations.AlterModelOptions(
            name='omniformemailhandler',
            options={'verbose_name': 'Send Static Email'},
        ),
        migrations.AlterField(
            model_name='omniformemailhandler',
            name='subject',
            field=models.CharField(help_text='The subject of the email that will be sent', max_length=255),
        ),
    ]
