# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-23 05:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('omniforms', '0021_email_handlers'),
    ]

    operations = [
        migrations.CreateModel(
            name='OmniForeignKeyFieldNew',
            fields=[
                ('omnifield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='omniforms.OmniField')),
                ('related_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'Foreign Key Field',
            },
            bases=('omniforms.omnifield',),
        ),
        migrations.CreateModel(
            name='OmniManyToManyFieldNew',
            fields=[
                ('omnifield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='omniforms.OmniField')),
                ('related_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'Many To Many Field',
            },
            bases=('omniforms.omnifield',),
        ),
    ]
