# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-23 06:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omniforms', '0023_copy_related_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OmniForeignKeyField',
        ),
        migrations.DeleteModel(
            name='OmniManyToManyField',
        ),
        migrations.DeleteModel(
            name='OmniRelatedField',
        ),
    ]
